export const ARCHIGNORE_DEFAULT_PATTERNS = [
  '# Arch ignore patterns',
  '# Lines starting with # are comments',
  '# Use !pattern to unignore a path',
  '',
  '# Dependencies',
  'node_modules/',
  '.pnpm-store/',
  '.npm/',
  '.yarn/',
  '',
  '# Build outputs',
  'dist/',
  'build/',
  'coverage/',
  '*config.ts',
  '*.tsbuildinfo',
  '',
  '# Tool caches',
  '.next/',
  '.nuxt/',
  '.svelte-kit/',
  '.parcel-cache/',
  '.cache/',
  '.turbo/',
  '.eslintcache',
  '',
  '# Runtime artifacts',
  'logs/',
  '*.log',
  '',
  '# VCS and arch output',
  '.git/',
  '.arch/',
]

export const ARCHIGNORE_DEFAULT_CONTENT = `${ARCHIGNORE_DEFAULT_PATTERNS.join('\n')}\n`
